// src/APP后台版/components/Sidebar.vue
<template>
  <div
    class="z-50 flex h-full w-20 shrink-0 flex-col items-center space-y-6 border-r border-blue-500/20 bg-gradient-to-b from-slate-900/80 to-black/80 py-6 backdrop-blur-xl"
  >
    <!-- Logo -->
    <div
      class="flex h-12 w-12 shrink-0 cursor-pointer items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-violet-600 shadow-lg shadow-blue-500/25 transition-transform hover:scale-105"
      @click="navigate('/play')"
      title="Go to Play"
    >
      <div class="h-6 w-6 rounded-sm bg-white"></div>
    </div>

    <!-- Menu Items -->
    <div class="flex flex-1 flex-col space-y-4">
      <button
        v-for="item in menuItems"
        :key="item.path"
        @click="navigate(item.path)"
        :title="item.label"
        :class="[
          'group relative flex h-12 w-12 items-center justify-center rounded-xl transition-all duration-300',
          isActive(item.path)
            ? 'border border-blue-400/30 bg-gradient-to-br from-blue-500/20 to-violet-600/20 shadow-lg shadow-blue-500/20'
            : 'border border-slate-700/50 bg-slate-800/50 hover:border-blue-500/30 hover:bg-slate-700/50',
        ]"
      >
        <i
          :class="[
            item.icon,
            'text-lg transition-colors duration-300',
            isActive(item.path) ? 'text-blue-400' : 'text-slate-400 group-hover:text-blue-400',
          ]"
        ></i>
        <div
          v-if="isActive(item.path)"
          class="absolute top-1/2 -right-1 h-6 w-1 -translate-y-1/2 transform rounded-full bg-gradient-to-b from-blue-400 to-violet-500"
        ></div>
      </button>
    </div>

    <!-- Bottom Actions (Theme Toggle) -->
    <div class="mt-auto flex flex-col space-y-4 pb-4">
      <button
        @click="toggleTheme"
        class="group relative flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border border-slate-700/50 bg-slate-800/50 transition-all duration-300 hover:border-blue-500/30 hover:bg-slate-700/50"
        :title="isDark ? 'Switch to Light Mode' : 'Switch to Dark Mode'"
      >
        <i :class="['fas', isDark ? 'fa-sun text-yellow-400' : 'fa-moon text-blue-400', 'text-lg transition-colors duration-300']"></i>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';

const router = useRouter();
const route = useRoute();
const isDark = ref(false);

const menuItems = [
  { icon: 'fas fa-gamepad', label: 'Play', path: '/play' },
  { icon: 'fas fa-home', label: 'Home', path: '/home' },
  { icon: 'fas fa-concierge-bell', label: 'Service', path: '/service' },
  { icon: 'fas fa-compass', label: 'Discover', path: '/discover' },
  { icon: 'fas fa-history', label: 'History', path: '/history' },
  { icon: 'fas fa-user', label: 'Me', path: '/me' },
];

function navigate(path: string) {
  router.push(path);
}

function isActive(path: string) {
  return route.path === path;
}

function toggleTheme() {
  isDark.value = !isDark.value;
  // Trigger global theme change event
  window.dispatchEvent(
    new CustomEvent('theme-change', {
      detail: { isDark: isDark.value },
    }),
  );
  // Persist theme
  localStorage.setItem('app-theme', isDark.value ? 'dark' : 'light');
}

function onThemeChange(event: any) {
  isDark.value = event.detail.isDark;
}

onMounted(() => {
  // Sync initial state
  const savedTheme = localStorage.getItem('app-theme');
  isDark.value = savedTheme === 'dark';

  // Listen for external theme changes
  window.addEventListener('theme-change', onThemeChange);
});

onUnmounted(() => {
  window.removeEventListener('theme-change', onThemeChange);
});
</script>

// 初始模板/UI参考/src/components/Sidebar.tsx
import { Search, TrendingUp, Plus, BarChart3, User, Heart } from "lucide-react";

const menuItems = [
  { icon: Search, label: "Search", active: false },
  { icon: TrendingUp, label: "Hot", active: true },
  { icon: Plus, label: "New", active: false },
  { icon: BarChart3, label: "Rising", active: false },
  { icon: User, label: "Profile", active: false },
  { icon: Heart, label: "Favorite", active: false },
];

export function Sidebar() {
  return (
    <div className="w-20 h-full bg-gradient-to-b from-slate-900/80 to-black/80 backdrop-blur-xl border-r border-blue-500/20 flex flex-col items-center py-6 space-y-6">
      {/* Logo */}
      <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-violet-600 rounded-xl flex items-center justify-center shadow-lg shadow-blue-500/25">
        <div className="w-6 h-6 bg-white rounded-sm"></div>
      </div>

      {/* Menu Items */}
      <div className="flex flex-col space-y-4">
        {menuItems.map((item) => {
          const Icon = item.icon;
          return (
            <button
              key={item.label}
              className={`w-12 h-12 rounded-xl flex items-center justify-center transition-all duration-300 relative group ${
                item.active
                  ? "bg-gradient-to-br from-blue-500/20 to-violet-600/20 border border-blue-400/30 shadow-lg shadow-blue-500/20"
                  : "bg-slate-800/50 hover:bg-slate-700/50 border border-slate-700/50 hover:border-blue-500/30"
              }`}
            >
              <Icon
                className={`w-6 h-6 transition-colors duration-300 ${
                  item.active ? "text-blue-400" : "text-slate-400 group-hover:text-blue-400"
                }`}
              />
              {item.active && (
                <div className="absolute -right-1 top-1/2 transform -translate-y-1/2 w-1 h-6 bg-gradient-to-b from-blue-400 to-violet-500 rounded-full"></div>
              )}
            </button>
          );
        })}
      </div>
    </div>
  );
}
